name: Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ] # default branch
    paths:
      - 'hexo-demo/**'

defaults:
  run:
    shell: bash
    working-directory: hexo-demo

jobs:
  bulidHexo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hexo-artifact
          path: hexo-demo/public

  deployHexo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for checkout
    needs: bulidHexo
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Get hexo artifact
        uses: actions/download-artifact@v3
        with:
          name: hexo-artifact
          path: hexo-demo/public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.HEXO_DEPLOY_TOKEN }}
          external_repository: thelittlesheep/thelittlesheep.github.io
          publish_dir: hexo-demo/public
      - name: GCP authentication
        uses: google-github-actions/auth@v0.8.1
        with:
          workload_identity_provider: '${{secrets.WORKLOAD_IDENTITY_PROVIDER}}'
          service_account: '${{secrets.SERVICE_ACCOUNT}}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0
      - name: Upload file to Cloud Storage
        run: |
          gsutil -m cp -r -c -z html,js,css hexo-demo/public/** ${{secrets.STORAGE_PATH}}